#!/bin/bash

# Sentinel Stack Interactive Setup
# Initializes org-config.yaml and guides first-time setup

set -e

echo "╔════════════════════════════════════════════════════════════╗"
echo "║       Sentinel Stack — Governance Setup Wizard             ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Check if config already exists
if [ -f "config/org-config.yaml" ]; then
    echo "⚠️  config/org-config.yaml already exists."
    read -p "Overwrite existing config? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Setup cancelled. Keeping existing config."
        exit 0
    fi
fi

# Collect company information
echo "📋 Company Information"
echo "─────────────────────────────────────────────────────────────"
read -p "Company name: " COMPANY_NAME
read -p "Company domain (e.g., company.com): " COMPANY_DOMAIN
read -p "Industry (e.g., Private Markets, Healthcare, Fintech, Legal): " COMPANY_INDUSTRY
read -p "Jurisdiction (e.g., US, EU, US/EU): " COMPANY_JURISDICTION
echo ""

# Collect governance contacts
echo "👥 Governance Contacts"
echo "─────────────────────────────────────────────────────────────"
read -p "Compliance Officer email: " COMPLIANCE_EMAIL
read -p "Security Officer (CISO) email: " CISO_EMAIL
read -p "CFO name (for Finance approvals): " CFO_NAME
read -p "General Counsel name (for Legal approvals): " COUNSEL_NAME
read -p "Chief People Officer name (for HR approvals): " CHRO_NAME
echo ""

# Collect DLP configuration
echo "🔒 Data Loss Prevention (DLP) Configuration"
echo "─────────────────────────────────────────────────────────────"
echo "DLP scores content sensitivity from 0-100."
echo "- alert_threshold: Score >= this → flag for review (default: 40)"
echo "- block_threshold: Score >= this → block request (default: 85)"
echo ""
read -p "Alert threshold (0-100, default 40): " ALERT_THRESHOLD
ALERT_THRESHOLD=${ALERT_THRESHOLD:-40}
read -p "Block threshold (0-100, default 85): " BLOCK_THRESHOLD
BLOCK_THRESHOLD=${BLOCK_THRESHOLD:-85}
echo ""

# Collect AI governance configuration
echo "🤖 AI Governance Configuration"
echo "─────────────────────────────────────────────────────────────"
echo "Risk appetite: What level of AI risk is acceptable?"
echo "  - minimal: Only allow simple AI tools"
echo "  - limited: Can use limited + high-risk AI (with oversight)"
echo "  - high: Can use most AI (with governance)"
echo ""
read -p "Organization risk appetite (minimal/limited/high): " RISK_APPETITE
RISK_APPETITE=${RISK_APPETITE:-limited}
echo ""

# Collect compliance frameworks
echo "✅ Compliance Frameworks"
echo "─────────────────────────────────────────────────────────────"
echo "Which compliance frameworks apply? (Select all that apply)"
FRAMEWORKS=()
read -p "  SOC 2 required? (y/N): " -n 1 -r
[[ $REPLY =~ ^[Yy]$ ]] && FRAMEWORKS+=("SOC2")
echo
read -p "  ISO 27001 required? (y/N): " -n 1 -r
[[ $REPLY =~ ^[Yy]$ ]] && FRAMEWORKS+=("ISO27001")
echo
read -p "  GDPR required? (y/N): " -n 1 -r
[[ $REPLY =~ ^[Yy]$ ]] && FRAMEWORKS+=("GDPR")
echo
read -p "  NIST CSF required? (y/N): " -n 1 -r
[[ $REPLY =~ ^[Yy]$ ]] && FRAMEWORKS+=("NIST_CSF")
echo
echo ""

# Generate config file
echo "📝 Generating config/org-config.yaml..."
echo ""

cat > config/org-config.yaml << EOF
# Sentinel Stack Organization Configuration
# Generated by setup.sh on $(date)
# Customize further in this file as needed

company:
  name: "$COMPANY_NAME"
  domain: "$COMPANY_DOMAIN"
  industry: "$COMPANY_INDUSTRY"
  jurisdiction: "$COMPANY_JURISDICTION"

dlp:
  industry_pack: "default"
  alert_threshold: $ALERT_THRESHOLD
  block_threshold: $BLOCK_THRESHOLD
  redact_secrets: true

guardrails:
  admin_contact: "$COMPLIANCE_EMAIL"
  escalation_contact: "$CISO_EMAIL"
  approvers:
    finance:
      primary: "$CFO_NAME"
      escalation: "CEO"
    legal:
      primary: "$COUNSEL_NAME"
      escalation: "Chief Legal Officer"
    hr:
      primary: "$CHRO_NAME"
      escalation: "CEO"

ai_governance:
  risk_appetite: "$RISK_APPETITE"
  prohibited_uses: []

compliance:
  frameworks:
EOF

# Add frameworks
for framework in "${FRAMEWORKS[@]}"; do
    echo "    - \"$framework\"" >> config/org-config.yaml
done

cat >> config/org-config.yaml << 'EOF'

audit_trail:
  retention_days: 2555
  retention_critical_days: 3650
EOF

echo "✅ Config created: config/org-config.yaml"
echo ""

# Next steps
echo "╔════════════════════════════════════════════════════════════╗"
echo "║                    Next Steps                              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "1️⃣  Review Configuration"
echo "   Open config/org-config.yaml and review:"
echo "   - Approver names and contacts"
echo "   - Industry pack selection"
echo "   - Compliance frameworks"
echo "   - DLP thresholds"
echo ""

echo "2️⃣  Choose Your Platform"
echo "   Set up Sentinel Stack on your preferred platforms:"
echo "   - ChatGPT (Custom GPT): See platforms/openai/README.md"
echo "   - Claude: Paste INSTRUCTIONS.md into your conversation"
echo "   - Google Gemini: See platforms/gemini/README.md"
echo "   - IDE (Cursor/VS Code): See platforms/cursor/README.md"
echo ""

echo "3️⃣  Train Your Team"
echo "   Create onboarding materials covering:"
echo "   - Data classification (what data types we protect)"
echo "   - Guardrails policy (when requests get blocked)"
echo "   - 4-Eyes review process (high-stakes decisions)"
echo "   - AI governance (assessing new AI tools)"
echo ""

echo "4️⃣  Set Up Monitoring"
echo "   - Configure org-config.yaml for alerts"
echo "   - Set up escalation contacts"
echo "   - Plan weekly review of guardrail decisions"
echo ""

echo "5️⃣  Read Key Documentation"
echo "   - ARCHITECTURE.md: How the system works"
echo "   - CUSTOMIZATION.md: Tuning by industry"
echo "   - SKILL-HIERARCHY.md: Skill dependencies"
echo ""

echo "📚 Full Documentation"
echo "   - README.md: Overview and quick start"
echo "   - INSTRUCTIONS.md: AI instructions for Sentinel Stack"
echo "   - docs/: Detailed guides"
echo "   - skills/: Individual skill documentation"
echo ""

echo "💬 Support & Questions"
echo "   Use the first-principles SKILL for novel governance questions"
echo "   Contact: $COMPLIANCE_EMAIL"
echo ""

echo "✨ Setup complete! You're ready to use Sentinel Stack."
echo ""
